Create dataset.json
Amsterdam/amsterdam-schema pull request #438
Opened 2022-06-14 06:48 UTC by Karin-Goes

2022-07-06 15:10 UTC, lbam commented on datasets/bag_azure/woonplaatsen/v2.0.0.json
> +
```suggestion
```

2022-07-11 10:58 UTC, jjmurre submitted a review, later dismissed
LGTM

2022-07-12 18:43 UTC, peteradrichem commented
@jjmurre Kan deze nu gemerged worden?

2022-08-23 07:34 UTC, JKoetsier commented
@jjmurre @lbam kan iemand deze mergen?

2022-08-23 07:43 UTC, lbam commented on datasets/bag_azure/woonplaatsen/v2.0.0.json
> +      "datumActeelTot": {
```suggestion
      "datumActueelTot": {	
```

2022-08-23 07:55 UTC, lbam commented
@JKoetsier Ik zag nog een tikfout in een veldnaam.

2022-08-23 08:59 UTC, lbam requested changes
De tabellen moeten nog een `mainGeometry` krijgen, omdat de geovelden niet `geometry` heten maar `geometrie`.

2022-08-23 11:13 UTC, lbam approved these changes

2022-08-23 11:13 UTC, merged