More BRP collections.
Amsterdam/amsterdam-schema pull request #653
Opened 2023-03-08 10:57 UTC by peteradrichem

- ouders
- kinderen
- huwelijkenpartnerschappen

2023-03-09 10:36 UTC, Yrob requested changes
kleine typo verder prima

2023-03-09 10:36 UTC, Yrob commented on datasets/brp_azure/huwelijkenpartnerschappen/v2.0.0.json
> +      "parnterIdentificatie": {
```suggestion
      "partnerIdentificatie": {
```

typo

2023-03-09 10:51 UTC, peteradrichem commented on datasets/brp_azure/huwelijkenpartnerschappen/v2.0.0.json
> +      "parnterIdentificatie": {
Thanks.

2023-03-09 10:52 UTC, peteradrichem commented on datasets/brp_azure/huwelijkenpartnerschappen/v2.0.0.json
> +      "parnterIdentificatie": {
Aangepast

2023-03-12 12:41 UTC, Yrob approved these changes

2023-03-12 12:41 UTC, merged

2023-03-12 13:41 UTC, peteradrichem commented
Thanks